on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Listing contents
        run: ls -lah
        
      - name: Install dependencies
        run: |
          cd frontend 
          npm ci

      - name: Build application
        run: |
          cd frontend 
          npm run build

      - name: Listing contents in frontend
        run: |
          cd frontend 
          ls -lah
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: frontend/dist/
